### ISSUE TITLE
The  json format of  Line Symbol for template parser have field redefinition

### ISSUE THREAD

**Issue by SinigLi** [erickzli/hex-parser#10]
**Describe the bug**
Such like the line symbol data for index-8-name-cartogline.data.
![image](https://user-images.githubusercontent.com/25496637/58613748-20281780-82e9-11e9-8d7c-13a895c997de.png)

It's templat parsed result is:
{
...other parsed infos.
template info:
                "template": {
                    "interval": 3.000000,
                    "linePatternFeature": {
                        "patternLength": 0.000000,
                        "gapLength": 1.000000
                    },
                    "linePatternFeature": {
                        "patternLength": 1.000000,
                        "gapLength": 1.000000
                    },
                    "linePatternFeature": {
                        "patternLength": 3.000000,
                        "gapLength": 4.000000
                    },
                    "linePatternFeature": {
                        "patternLength": 2.000000,
                        "gapLength": 3.000000
                    }
                }
...
This linePatternFeature filed is redefinition,which is invalid for json parser.

**Comment by erickzli** [comment]
I converted it into a list form.
