### ISSUE TITLE
Line symbol which only has one layer contained in fill symbols,it will lost layer Activeness info

### ISSUE THREAD

**Issue by SinigLi** [erickzli/hex-parser#11]
**Describe the bug**
**Not only the line symbol which contained in fill symbols lost activeness info,And marked symbols which contained in line symbol the same.** 

**Screenshots**
**just like this is the fill symbol,some line symbol is contained in it:**
![image](https://user-images.githubusercontent.com/25496637/58686905-b70cd680-83b2-11e9-95ff-fec2860291cc.png)
the fill line symbol(only has one layer):
![image](https://user-images.githubusercontent.com/25496637/58686953-da378600-83b2-11e9-8b34-03f86a68f7ad.png)

**the parsed result:**
           "lineProperties_fillingLine": {
                "name": "Filling Line",
                "numberOfLineLayers": 1,
                "lineLayer": [
                    {
                        "number": 1,
                        "type": "Simple Line",
                        "color_simpleLineColor": {
                            "name": "Simple Line Color",
                            "space": "RGB",
                            "firstField": 91.231851,
                            "secondField": -49.888863,
                            "thirdField": 80.838943
                        },
                        "width": 1.000000,
                        "style": "Solid"
                    }
                ]
            },
            "lineProperties_outline": {
                "name": "Outline",
                "numberOfLineLayers": 1,
                "lineLayer": [
                    {
                        "number": 1,
                        "type": "Simple Line",
                        "color_simpleLineColor": {
                            "name": "Simple Line Color",
                            "space": "RGB",
                            "firstField": 54.043767,
                            "secondField": 0.000000,
                            "thirdField": 0.000000
                        },
                        "width": 1.000000,
                        "style": "Solid"
                    }
                ]
            },

the fill line and outline don't have the activeness infos .

**Comment by erickzli** [comment]
Sometimes the symbol file just doesn’t have that info, but I’ll definitely check it out.
