### ISSUE TITLE
Add support for parsing activeness of fill layers

### ISSUE THREAD

**Issue by erickzli** [erickzli/hex-parser#2]

**Comment by SinigLi** [comment]
The activeness values of fill layers is inverse.
The layers activeness like this:
![image](https://user-images.githubusercontent.com/25496637/58679879-f548cc80-8397-11e9-9887-3ccfd4185e06.png)
first layer and third layer is in active，second layer is inactived.
But,really the parsed result is:
    "fillLayerActiveness": {
        "layer1": 0,
        "layer2": 1,
        "layer3": 0
    }
Result is inverse.

**Comment by erickzli** [comment]
Yes, I will take a look into it. Thanks!

**Comment by SinigLi** [comment]
But what interesting I found is that the activeness result of line fill symbol is correctly.
Such like this:
![image](https://user-images.githubusercontent.com/25496637/58686008-1cab9380-83b0-11e9-9953-a49cab2bf636.png)
activeness result:
    "fillLayerActiveness": {
        "layer1": 1
    }
