### ISSUE TITLE
The grandParser function should support to parser the other symbols.

### ISSUE THREAD

**Issue by SinigLi** [erickzli/hex-parser#8]
**Is your feature request related to a problem? Please describe.**
The Marked symbols and Line symbols are as importance as the Fill Symbol.
But currently,The parser function only be supported to analysis Fill Symbol.If there were some binary datas of Line Symbol or Marked Symbol to parser,it always get some err result.

**Describe the solution you'd like**
The grandParser function could support analysis the Marked Symbol and Line Symbol binary data.
And return the Json string should corresponding with the symbol type.

**Comment by erickzli** [comment]
That is the function I am implementing. I believe it will be done before tomorrow. :)

**Comment by erickzli** [comment]
The version that fulfills the request has been uploaded. Please check v0.10.
