### ISSUE TITLE
The result of the parser which marked of character   is invalid

### ISSUE THREAD

**Issue by SinigLi** [erickzli/hex-parser#9]
**Describe the bug**
There are some symbol styles in the test_style.style.
And the index-7-name-charmarked.data files contain the binary datas of the marker symbols which name is charmarked.
It Parse failure.

**Screenshots**
![image](https://user-images.githubusercontent.com/25496637/58611101-9aa06980-82e0-11e9-9b0e-22b22e738a53.png)

**test files**

**Comment by erickzli** [comment]
Looks like the program should have supported parsing Chinese characters. They are encoded by unicodes.

**Comment by SinigLi** [comment]
Maybe you could ignore the encode ,just  return the origin char data ,the encoded by may side is more easier.But you have to promise it can parser correctly.

**Comment by erickzli** [comment]
> Maybe you could ignore the encode ,just return the origin char data ,the encoded by may side is more easier.But you have to promise it can parser correctly.

Yeah, either way. I will let you know about it, then.
